name: Excel Monitor and Email Notification

on:
  schedule:
    - cron: "*/15 * * * *"  # UTC 时间每15分钟运行一次
  workflow_dispatch:         # 保留手动触发功能

jobs:
  process-excel:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # 确保有推送代码的权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 保留 Git 凭证用于后续推送
          fetch-depth: 0             # 获取完整提交历史（避免分支检测问题）

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Run script
        env:
          EXCEL_URL: ${{ secrets.EXCEL_URL }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python scripts/main.py

      - name: Commit and Push Changes
        if: success()  # 仅在脚本运行成功时执行
        run: |
          # 仅在 last_row.txt 有变更时提交
          if git diff --exit-code --quiet -- last_row.txt; then
            echo "::notice:: 没有检测到变更，跳过提交"
          else
            echo "::info:: 检测到变更，执行提交..."
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add last_row.txt
            git commit -m "Auto-update last processed row"
            git pull --rebase  # 防止因远程变更导致冲突
            git push origin HEAD:main
            echo "::notice:: 变更已推送至仓库"
          fi
