name: Excel Monitor and Email Notification

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  process-excel:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限配置

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 保留凭证

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Run script
        env:
          EXCEL_URL: ${{ secrets.EXCEL_URL }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python scripts/main.py

      - name: Commit state file
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last_row.txt
          git commit -m "Update last processed row"
          git push origin HEAD:main
